import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://mseyzpycqbbnoltrrnzd.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZXl6cHljcWJibm9sdHJybnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3ODcwMTQsImV4cCI6MjA5NDM2MzAxNH0.pfhjy5AVnFe6a0cWHJwwB3Ql_o2OaL4IFN2aYt2Odxc'
);

const hackathons = [
  { name: "QIE Blockchain Hackathon", organizer: "QIE Digital", description: "Blockchain development competition encouraging decentralized infrastructure and application experimentation.", prize_pool: "$20,000", deadline: "2026-05-15", deadline_text: null, category: "Web3", format: "Online", free_to_enter: true, apply_url: "https://hackathon.qie.digital/", spotlight: false, verified: false },
  { name: "Mezo Hackathon: Building Bitcoin's Future", organizer: "Encode Club", description: "Bitcoin ecosystem hackathon focused on infrastructure, scaling, and BTC-native applications.", prize_pool: "$30,000", deadline: "2026-05-15", deadline_text: null, category: "Web3", format: "Online", free_to_enter: true, apply_url: "https://www.encodeclub.com/programmes/mezo-hackathon-building-bitcoins-future", spotlight: false, verified: false },
  { name: "The Eitherway Hackathon", organizer: "Eitherway", description: "Consumer dApp-focused side track connected to the Solana Frontier ecosystem.", prize_pool: "$20,000", deadline: "2026-05-15", deadline_text: null, category: "Web3", format: "Online", free_to_enter: true, apply_url: "https://superteam.fun/earn/hackathon/frontier", spotlight: false, verified: false },
  { name: "UC Berkeley AI Hackathon", organizer: "Hack Berkeley", description: "University-led AI hackathon featuring startup opportunities, mentorship, and technical challenges.", prize_pool: "$100,000", deadline: "2026-05-17", deadline_text: null, category: "AI", format: "In-Person", free_to_enter: true, apply_url: "https://ai.hackberkeley.org/", spotlight: false, verified: false },
  { name: "Midnight Hackathon", organizer: "Midnight", description: "Privacy-focused blockchain hackathon exploring confidential applications and ZK systems.", prize_pool: "Undisclosed", deadline: "2026-05-17", deadline_text: null, category: "Web3", format: "Online", free_to_enter: true, apply_url: "https://events.mlh.io/events/14061-midnight-hackathon-may-2026", spotlight: false, verified: false },
  { name: "Gemma 4 Good Hackathon", organizer: "Google DeepMind x Kaggle", description: "AI-for-good competition powered by Google DeepMind's Gemma models and Kaggle's global builder ecosystem.", prize_pool: "$200,000", deadline: "2026-05-18", deadline_text: null, category: "AI", format: "Online", free_to_enter: true, apply_url: "https://www.kaggle.com/competitions/gemma-4-good-hackathon", spotlight: false, verified: true },
  { name: "Build with MeDo Hackathon", organizer: "MeDo", description: "AI-focused hackathon encouraging builders to create practical productivity and automation applications.", prize_pool: "$50,000", deadline: "2026-05-20", deadline_text: null, category: "AI", format: "Online", free_to_enter: true, apply_url: "https://medo.devpost.com/", spotlight: false, verified: false },
  { name: "AI Agent Olympics", organizer: "Milan AI Week / lablab.ai", description: "AI agent competition hosted during Milan AI Week focused on autonomous systems and intelligent workflows.", prize_pool: "$28,000", deadline: "2026-05-20", deadline_text: null, category: "AI", format: "Hybrid", free_to_enter: true, apply_url: "https://lablab.ai/ai-hackathons/", spotlight: false, verified: false },
  { name: "FlagOS Open Computing Global Challenge", organizer: "DoraHacks", description: "Open-source AI infrastructure challenge focused on compute systems and decentralized workflows.", prize_pool: "$287,000", deadline: "2026-05-20", deadline_text: null, category: "Both", format: "Online", free_to_enter: true, apply_url: "https://dorahacks.io/hackathon/flagos-open-computing/detail", spotlight: false, verified: true },
  { name: "Reddit Mod Tools Hackathon", organizer: "Reddit", description: "Reddit-focused hackathon for moderation tooling, migrated applications, and community infrastructure.", prize_pool: "$45,000", deadline: "2026-05-27", deadline_text: null, category: "AI", format: "Online", free_to_enter: true, apply_url: "https://mod-tools-migration.devpost.com/", spotlight: false, verified: false },
  { name: "ElevenHacks Hackathon", organizer: "ElevenLabs", description: "Voice AI hackathon focused on speech synthesis, conversational systems, and audio applications.", prize_pool: "$240,000", deadline: "2026-05-28", deadline_text: null, category: "AI", format: "Online", free_to_enter: true, apply_url: "https://hacks.elevenlabs.io/", spotlight: false, verified: true },
  { name: "DevNetwork AI + ML Hackathon", organizer: "DevNetwork", description: "AI and machine learning hackathon focused on practical applications, tooling, and developer workflows.", prize_pool: "$12,500", deadline: "2026-05-28", deadline_text: null, category: "AI", format: "Hybrid", free_to_enter: true, apply_url: "https://devnetwork-ai-ml-hack-2026.devpost.com/", spotlight: false, verified: false },
  { name: "Hack4freedom", organizer: "Hack4freedom", description: "Freedom-tech focused hackathon encouraging innovative solutions across AI and decentralized systems.", prize_pool: "$5,000", deadline: "2026-05-30", deadline_text: null, category: "Both", format: "Online", free_to_enter: true, apply_url: "https://www.hack4freedom.com/", spotlight: false, verified: false },
  { name: "BAGS Hackathon", organizer: "BagsApp", description: "Large-scale grant-backed hackathon where top projects receive funding, incubation, and ecosystem support.", prize_pool: "$4,000,000", deadline: "2026-06-01", deadline_text: null, category: "Both", format: "Online", free_to_enter: true, apply_url: "https://bags.fm/hackathon", spotlight: false, verified: false },
  { name: "Anthropic AI Hackathon", organizer: "Anthropic x lablab.ai", description: "Claude-powered AI hackathon focused on agentic workflows, reasoning systems, and AI product development.", prize_pool: "Undisclosed", deadline: "2026-06-02", deadline_text: null, category: "AI", format: "Online", free_to_enter: true, apply_url: "https://lablab.ai/ai-hackathons/", spotlight: false, verified: true },
  { name: "Google Cloud Rapid Agent Hackathon", organizer: "Google Cloud", description: "AI agent hackathon powered by Google Cloud focused on scalable intelligent systems.", prize_pool: "$60,000", deadline: "2026-06-11", deadline_text: null, category: "AI", format: "Online", free_to_enter: true, apply_url: "https://rapid-agent.devpost.com/", spotlight: false, verified: true },
  { name: "NandaHack Agentic AI Phase 2", organizer: "MIT Media Lab x HCLTech", description: "Agentic AI hackathon focused on intelligent systems, research innovation, and enterprise AI applications.", prize_pool: "Undisclosed", deadline: "2026-06-13", deadline_text: null, category: "AI", format: "Hybrid", free_to_enter: true, apply_url: "https://www.media.mit.edu/events/nanda-hackathon/", spotlight: false, verified: false },
  { name: "ETHGlobal New York", organizer: "ETHGlobal", description: "Major ETHGlobal event bringing together Ethereum developers, startups, and protocol ecosystems.", prize_pool: "$100,000", deadline: "2026-06-14", deadline_text: null, category: "Web3", format: "In-Person", free_to_enter: true, apply_url: "https://ethglobal.com/", spotlight: false, verified: true },
  { name: "Mantle Turing Test Hackathon Phase 2", organizer: "Mantle", description: "AI agent and on-chain intelligence hackathon exploring autonomous blockchain systems.", prize_pool: "$100,000", deadline: "2026-06-15", deadline_text: null, category: "Both", format: "Online", free_to_enter: true, apply_url: "https://dorahacks.io/hackathon/mantleturingtesthackathon2026/detail", spotlight: false, verified: false },
  { name: "Gnosis Agentic Ethereum Hackathon", organizer: "GnosisDAO", description: "Ethereum and AI hackathon centered around autonomous agents and on-chain coordination.", prize_pool: "$40,000", deadline: "2026-06-15", deadline_text: null, category: "Both", format: "Online", free_to_enter: true, apply_url: "https://ethglobal.com/events/agents", spotlight: false, verified: false },
  { name: "FIND EVIL", organizer: "Devpost", description: "Cybersecurity and AI hackathon focused on threat detection, analysis, and intelligent security systems.", prize_pool: "$22,000", deadline: "2026-06-15", deadline_text: null, category: "Both", format: "Online", free_to_enter: true, apply_url: "https://findevil.devpost.com/", spotlight: false, verified: false },
  { name: "Agentathon", organizer: "Encode Club", description: "AI agent hackathon and builder program for autonomous workflows and intelligent systems.", prize_pool: "$5,000", deadline: "2026-06-20", deadline_text: null, category: "AI", format: "Online", free_to_enter: true, apply_url: "https://www.encodeclub.com/programmes/agentathon", spotlight: false, verified: false },
  { name: "Smart Commerce Infrastructure Challenge", organizer: "Ignyte x Polygon", description: "Blockchain commerce infrastructure challenge focused on merchant payments and SME trade finance.", prize_pool: "$25,000", deadline: "2026-07-12", deadline_text: null, category: "Web3", format: "Online", free_to_enter: true, apply_url: "https://app.ignyte.ae/public/challenges/4FB1DBBF-1833-F111-9A49-6045BD14D400", spotlight: false, verified: false },
  { name: "Polygon AggLayer Builder Events", organizer: "Polygon", description: "AggLayer-focused ecosystem builder events centered around interoperability and cross-chain development.", prize_pool: "Undisclosed", deadline: null, deadline_text: "Rolling", category: "Both", format: "Hybrid", free_to_enter: true, apply_url: "https://www.agglayer.dev/events", spotlight: false, verified: true },
  { name: "Aave GHO Stablecoin Payment Sprint", organizer: "Aave Grants DAO", description: "Stablecoin-focused builder sprint encouraging GHO-powered payment and DeFi infrastructure applications.", prize_pool: "$17,000", deadline: null, deadline_text: "TBD", category: "Web3", format: "Online", free_to_enter: true, apply_url: "https://aave.com/grants", spotlight: false, verified: false },
  { name: "GenDigital x Eazo x Photon AI Hackathon", organizer: "GenDigital x Eazo x Photon", description: "Large-scale AI hackathon focused on next-generation AI applications and startup experimentation.", prize_pool: "$300,000", deadline: null, deadline_text: "TBD", category: "AI", format: "Online", free_to_enter: true, apply_url: "https://lu.ma/frw43jmv", spotlight: false, verified: false },
  { name: "NYC Agent Hack", organizer: "Agentic Engineering", description: "New York-based AI hackathon focused on agent engineering and autonomous AI workflows.", prize_pool: "$45,000", deadline: null, deadline_text: "TBD", category: "AI", format: "In-Person", free_to_enter: true, apply_url: "https://lu.ma/nycagenthack", spotlight: false, verified: false },
  { name: "APAC Stellar Hackathon", organizer: "Rise In x Stellar", description: "Stellar ecosystem hackathon focused on decentralized finance, payments, and Web3 infrastructure.", prize_pool: "$60,000", deadline: null, deadline_text: "TBD", category: "Web3", format: "Online", free_to_enter: true, apply_url: "https://www.risein.com/programs/apac-stellar-hackathon/", spotlight: false, verified: false },
  { name: "XAGT AI Hackathon", organizer: "XAGT AI", description: "AI-focused hackathon exploring intelligent agents, automation, and next-generation AI products.", prize_pool: "$6,000", deadline: null, deadline_text: "TBD", category: "AI", format: "Online", free_to_enter: true, apply_url: "https://xagt.ai/hackathon", spotlight: false, verified: false },
  { name: "Poolside AI Hackathon", organizer: "Poolside AI", description: "AI engineering-focused hackathon with NVIDIA DGX Spark as the prize.", prize_pool: "NVIDIA DGX Spark", deadline: null, deadline_text: "TBD", category: "AI", format: "Online", free_to_enter: true, apply_url: "https://lu.ma/poolsidehackathon", spotlight: false, verified: false },
  { name: "Arc Network Builder Challenge", organizer: "Arc Network", description: "Blockchain infrastructure and ecosystem builder challenge.", prize_pool: "$50,000", deadline: null, deadline_text: "TBD", category: "Web3", format: "Online", free_to_enter: true, apply_url: "https://lu.ma/7i50p2r9", spotlight: false, verified: false },
];

async function seed() {
  console.log(`Seeding ${hackathons.length} hackathons…`);
  const { data, error } = await supabase.from('hackathons').insert(hackathons).select('id, name');
  if (error) {
    console.error('Seed failed:', error.message);
    process.exit(1);
  }
  console.log(`Inserted ${data?.length ?? 0} rows.`);
}

seed();
